$mainMod = SUPER

$terminal = ghostty +new-window
$browser = zen-browser
$fileManager = nautilus
$menu = rofi -show

bindl = $mainMod, return, exec, $terminal
bindl = $mainMod, B, exec, $browser
bindl = $mainMod, C, killactive,
bindl = $mainMod, Q, exit,
bindl = $mainMod, E, exec, $fileManager
bindl = $mainMod, space, exec, $menu

bindl = $mainMod, h, movefocus, l
bindl = $mainMod, l, movefocus, r
bindl = $mainMod, k, movefocus, u
bindl = $mainMod, j, movefocus, d

bindl = $mainMod, 1, workspace, 1
bindl = $mainMod, 2, workspace, 2
bindl = $mainMod, 3, workspace, 3
bindl = $mainMod, 4, workspace, 4
bindl = $mainMod, 5, workspace, 5
bindl = $mainMod, 6, workspace, 6
bindl = $mainMod, 7, workspace, 7
bindl = $mainMod, 8, workspace, 8
bindl = $mainMod, 9, workspace, 9
bindl = $mainMod, 0, workspace, 10

bindl = ALT SHIFT, 1, movetoworkspace, 1
bindl = ALT SHIFT, 2, movetoworkspace, 2
bindl = ALT SHIFT, 3, movetoworkspace, 3
bindl = ALT SHIFT, 4, movetoworkspace, 4
bindl = ALT SHIFT, 5, movetoworkspace, 5
bindl = ALT SHIFT, 6, movetoworkspace, 6
bindl = ALT SHIFT, 7, movetoworkspace, 7
bindl = ALT SHIFT, 8, movetoworkspace, 8
bindl = ALT SHIFT, 9, movetoworkspace, 9
bindl = ALT SHIFT, 0, movetoworkspace, 10

bindl = $mainMod, mouse_down, workspace, e+1
bindl = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = ,F1, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ -l 1.5
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -n2 set 5%-

bind = ,Print, exec, hyprshot -m output -t 2000 -o ~/Pictures/Screenshots/
bind = $mainMod, Print, exec, hyprshot -m region -t 2000 -o ~/Pictures/Screenshots/
