local opt = vim.opt

vim.g.have_nerd_font = true
opt.number = true
opt.relativenumber = true
opt.numberwidth = 4
opt.signcolumn = "yes"
opt.wrap = false
opt.scrolloff = 10
opt.sidescrolloff = 8
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.softtabstop = 2
opt.smartindent = true
opt.breakindent = true
opt.backup = false
opt.showcmd = false
opt.showmode = false
opt.cmdheight = 0
opt.laststatus = 2
opt.backspace = { "start", "eol", "indent" }
opt.clipboard:append("unnamedplus")
opt.fileencoding = "utf-8"
opt.wildignore:append({ "*/node_modules/*" })
opt.mouse = ""
opt.termguicolors = true
opt.splitbelow = true
opt.splitright = true
opt.timeoutlen = 400
opt.undofile = true
opt.updatetime = 50
opt.writebackup = false
opt.cursorline = true
opt.hlsearch = true
opt.incsearch = true
opt.inccommand = "split"
opt.smartcase = true
opt.ignorecase = true
